

services:
  frontend:
    volumes:
      - ./frontend:/app  # Mount frontend code for hot reloading
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes in Docker
    command: ["npm", "start"]  # Starts the React app in development mode with hot reloading

  backend:
    volumes:
      - ./backend:/app  # Mount backend code for instant updates
    environment:
      - FLASK_ENV=development  # Enable Flask debug mode
    command: ["python3", "app.py"]  # Ensure Flask auto-reloads on code changes
