lm_studio:
  base_url: "http://localhost:3000"
  api_key: "lm-studio"

prompt_template: |
  [INST] You are a precise email parsing assistant. Extract and format the following information from the email below, matching the fields of our intake form exactly. Use only information explicitly stated in the email. Mark required fields with an asterisk (*). Use "N/A" if information is not found.

  Email content:
  {{email_content}}

  Format the response exactly as follows:

  **ASSIGNER INFORMATION**
  - Assigner Name*: 
  - Assigner Email*: 
  - Assigner Phone*: 
  - Assigner Phone Extension: 

  **ASSIGNMENT INFORMATION**
  - Claim Number*: 
  - Policy Number: 
  - Date of Loss*: 
  - Client (Assigner's Company)*: 
  - Insurance Carrier*: 
  - Insured's Name*: 
  - Insured's Phone Number 1*: 
  - Insured's Phone Number 2: 
  - Insured's Email: 
  - Address of Risk Location*: 
  - Is this related to a CAT event?*:
  - CAT Event Name: 

  **ADDITIONAL PARTY INFORMATION**
  - Additional Party Name: 
  - Additional Party Company: 
  - Additional Party Phone: 
  - Additional Party Email: 

  **DESCRIPTION OF SERVICES NEEDED**
  - Describe the services needed*: 
  - Type of Expert Needed*: 
  - Type of Damage*: 
  - Areas of Property to Inspect*: 

  **QUESTIONS TO HELP US SPEED UP ASSIGNMENT PROCESSING**
  - Is a budget required before proceeding?*:
  - Number of Buildings/Units (if commercial): 
  - Call Required Before Inspection: 
  - Call Required After Inspection: 
  - Repair Recommendations Needed: 
  - Cost Estimate Required: 
  - Permission for Third-Party Tarp Removal: 
  - Tile Matching Information (for tile roof): 
  - Roof Diagram Needed: 
  
  **OTHER**
  - Notes/Comments: 
  - Attachments: 

  Fill in each field with information from the email only. Use "N/A" if not found. [/INST]

field_validation:
  assigner_name_pattern: '^[A-Za-z\\s]+$'
  assigner_email_pattern: '^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$'
  assigner_phone_pattern: '^\\d{3}-\\d{3}-\\d{4}$'
  assigner_phone_extension_pattern: '^\\d+$'
  claim_number_pattern: '^BX-\\d{8}$'
  policy_number_pattern: '^BCR-\\d{4}-\\d{5}$'
  date_of_loss_pattern: '^(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}(st|nd|rd|th)?, \\d{4}$'
  client_company_pattern: '^[A-Za-z\\s]+$'
  insurance_carrier_pattern: '^[A-Za-z\\s]+$'
  insured_name_pattern: '^[A-Za-z\\s]+$'
  insured_phone_pattern: '^\\d{3}-\\d{3}-\\d{4}$'
  insured_email_pattern: '^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$'
  risk_location_pattern: '^.+$'
  cat_event_related_pattern: '^(Yes|No)$'
  cat_event_name_pattern: '^[A-Za-z\\s]+$'
  additional_party_name_pattern: '^[A-Za-z\\s]+$'
  additional_party_company_pattern: '^[A-Za-z\\s]+$'
  additional_party_phone_pattern: '^\\d{3}-\\d{3}-\\d{4}$'
  additional_party_email_pattern: '^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$'
  services_needed_pattern: '^.+$'
  expert_needed_pattern: '^.+$'
  damage_type_pattern: '^.+$'
  property_inspect_pattern: '^.+$'
  budget_required_pattern: '^(Yes|No)$'
  number_of_buildings_pattern: '^\\d+$'
  call_before_inspection_pattern: '^(Yes|No)$'
  call_after_inspection_pattern: '^(Yes|No)$'
  repair_recommendations_pattern: '^(Yes|No)$'
  cost_estimate_pattern: '^(Yes|No)$'
  permission_tarp_removal_pattern: '^(Yes|No)$'
  tile_matching_pattern: '^.+$'
  roof_diagram_pattern: '^(Yes|No)$'
  notes_comments_pattern: '^.*$'
  attachments_pattern: '^.*$'

logging:
  level: "DEBUG"
  file_path: "logs/parser.log"
  create_logs_dir_if_not_exists: True

cache_dir: "./cache"
max_tokens: 8024
